language: python

sudo: required
before_install:
  - sudo apt-get install -y sshpass
addons:
  apt:
    update: true

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.49/hugo_0.49_Linux-64bit.tar.gz
  - tar xvf hugo*.tar.gz
  - pip install Pygments

script:
  - ./hugo

after_success:
  - rsync -r --rsh="/usr/bin/sshpass -p ${SFTP_PASSWORD}
    ssh -o StrictHostKeyChecking=no -l ${SFTP_USER}"
    ftp.itimo.xyz:public public
  - rsync -r --rsh="/usr/bin/sshpass -p ${SFTP_PASSWORD}
    ssh -o StrictHostKeyChecking=no -l ${SFTP_USER}"
    ftp.itimo.xyz:static static
